<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DuckNote.Scan</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\oui-builtin.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Management.Infrastructure" Version="3.0.0" />
  </ItemGroup>

</Project>
